1. TowTruck.all
2. Vehicle.find(3)
3. Vehicle.find_by vin: "D0985DF1593A350A4"
4. Vehicle.order(:acquired_at)
5. Vehicle.where(color: "silver").order(:make)
6. Vehicle.where(color: "red", make: "Honda", category: "car")
7. Vehicle.count(category: "motorcycle")
8. Vehicle.count(release_at: nil)
9. TowTruck.where("mileage > 200000")
10. TowTruck.where("last_service_at < '#{DateTime.now - 8.month}'")
11. Vehicle.average(:fee)
12. Vehicle.where.not(fee: nil).order(fee: :desc).first(3)
13. Vehicle.where.not(fee: nil).where(is_paid: false)
14. Vehicle.where.not(released_at: nil).order(:released_at)
15. Vehicle.where.not(notes: "")
16. Vehicle.where("year < 2000").select(:vin)
17. Vehicle.where(color: "silver").select(:make,:model,:year).order(:year)
18. Vehicle.sum(:fee)